swagger: '2.0'
info:
  title: cocurrent
  description: illustrate the intersection of properties of database objects
  termsOfService: only registered users are allowed to use this api
  contact:
    name: Caraway Support
    url: https://caraway.work
    email: greg@luzene.com
  version: '1'
host: localhost:8080
basePath: /cocurrent
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /intersect:
    get:
      tags:
        - intersect
      description: return sets and their labels
      responses:
        '200':
          description: list of sets and labels
          schema:
            type: array
            items:
              $ref: '#/definitions/FlagSetDTO'
    post:
      tags:
        - intersect
      description: upload csv file and aggregate into sets
      consumes:
        - multipart/form-data
      parameters:
        -
          name: rows
          in: formData
          description: records to intersect
          required: true
          type: file
      responses:
        '201':
          description: create sets and labels
          schema:
            type: array
            items:
              $ref: '#/definitions/FlagSetDTO'
  /progress:
    get:
      tags:
        - intersect
      description: upload progress (NOT SAFE FOR CONCURRENCY)
      responses:
        '200':
          description: return a json object containing computation progress
          schema:
            type: object
            properties:
              progress:
                type: number
tags:
  - progress
  - intersect

definitions:
  FlagSetDTO:
    type: object
    properties:
      labels:
        type: array
        items:
          type: string
      size:
        type: integer
  FlagSet:
    type: object
    properties:
      label:
        type: string
      members:
        type: array
        items:
          type: integer
  Flag:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      value:
        type: boolean
